# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: license
kind: pipeline
type: docker
node:
   performance: low
clone:
  depth: 1
steps:
  - name: check
    image: docker.io/library/golang:1.21
    pull: always
    commands:
      - go install github.com/google/addlicense@v1.1.1
      - addlicense -c "SIGHUP s.r.l" -v -l bsd --check .

---
name: linting
kind: pipeline
type: docker
node:
   performance: low
depends_on:
  - license
clone:
  depth: 1
platform:
  os: linux
  arch: amd64
volumes:
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: render
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    environment:
      MISE_DATA_DIR: /mise-data
      MISE_OVERRIDE_CONFIG_FILENAMES: "mise.ci.toml"
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - |
        mise use kustomize@5.6.0
        eval "$(mise activate bash --shims)"
      - kustomize build katalog/cluster-autoscaler/base > cluster-autoscaler-base.yml
      - kustomize build katalog/cluster-autoscaler/v1.29.x > cluster-autoscaler-v1.29.yml
      - kustomize build katalog/cluster-autoscaler/v1.30.x > cluster-autoscaler-v1.30.yml
      - kustomize build katalog/cluster-autoscaler/v1.31.x > cluster-autoscaler-v1.31.yml
      - kustomize build katalog/cluster-autoscaler/v1.32.x > cluster-autoscaler-v1.32.yml
      - kustomize build katalog/cluster-autoscaler/v1.33.x > cluster-autoscaler-v1.33.yml
      - kustomize build katalog/load-balancer-controller > load-balancer-controller.yml
      - kustomize build katalog/node-termination-handler > node-termination-handler.yml

  - &check-deprecated-apis
    name: check-deprecated-apis
    image: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5
    pull: always
    depends_on:
      - render
    commands:
      # we use --ignore-deprecations because we don't want the CI to fail when the API has not been removed yet.
      - /pluto detect $${KUBERNETES_MANIFESTS} --ignore-deprecations --target-versions=k8s=v1.33.0
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-base.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-cluster-autoscaler-v129
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-v1.29.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-cluster-autoscaler-v130
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-v1.30.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-cluster-autoscaler-v131
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-v1.31.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-cluster-autoscaler-v132
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-v1.32.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-cluster-autoscaler-v133
    environment:
      KUBERNETES_MANIFESTS: cluster-autoscaler-v1.33.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-load-balancer-controller
    environment:
      KUBERNETES_MANIFESTS: load-balancer-controller.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-node-termination-handler
    environment:
      KUBERNETES_MANIFESTS: node-termination-handler.yml

---
name: release
kind: pipeline
type: docker
node:
   performance: low
clone:
  depth: 1

depends_on:
  - linting

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: prepare-tar-gz
    image: alpine:latest
    pull: always
    depends_on: [clone]
    commands:
      - tar -zcvf kubernetes-fury-aws-${DRONE_TAG}.tar.gz katalog/ LICENSE README.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [clone]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - kubernetes-fury-aws-${DRONE_TAG}.tar.gz
      prerelease: true
      overwrite: true
      title: "Preview ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - kubernetes-fury-aws-${DRONE_TAG}.tar.gz
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**